Project/PingPing/PingPing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls2/', include('polls2.urls')),
    path('admin/', admin.site.urls),
]

Project/PingPing/polls2/urls.py
from django.urls import path

from . import views

app_name = 'polls2'
urlpatterns = [
    # ex: /polls2/
    path('', views.IndexView.as_view(), name='index'),

    # ex: /polls2/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detailofques'),

    # ex: /polls2/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),

    # ex: /polls2/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

Project/PingPing/polls2/models.py
from django.db import models
from django.utils import timezone
import datetime

# python manage.py runserver


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        # return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

Project/PingPing/polls2/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from .models import Question, Choice
from django.utils import timezone


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        latest_question_list = Question.objects.filter(pub_date__lte=timezone.now(),)

        return latest_question_list.order_by('-pub_date')[:5]
        # return Question.objects.all
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     # output = ', '.join([q.question_text for q in latest_question_list])
#     # return HttpResponse(output)
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return render(request, 'polls/index.html', context)


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())
# def detail(request, ques_id):
#     question = get_object_or_404(Question, pk=ques_id)
#     return render(request, 'polls/detail.html', {'question':question})


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/res.html'

    def get_queryset(self):
        # only return question that has choices
        return Question.objects.filter(pub_date__lte=timezone.now())
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/res.html', {'question': question})


def vote(request, question_id):
    print("______")
    question = get_object_or_404(Question, pk=question_id)
    x = 'x' in request.POST
    o = 'o' in request.POST
    print(x)
    if o:
        try:
            selected_choice = question.choice_set.get(pk=request.POST['choiceID'])
        except (KeyError, Choice.DoesNotExist):
            # Redisplay the question voting form.
            return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': "You didn't select a choice.",
            })
        else:
            selected_choice.votes += 1
            selected_choice.save()
            return HttpResponseRedirect(reverse('polls2:results', args=(question.id,)))
    if x:
        latest_question_list = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
        # output = ', '.join([q.question_text for q in latest_question_list])
        # return HttpResponse(output)
        context = {
            'latest_question_list': latest_question_list,
        }
        return render(request, 'polls/index.html', context)
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.

Project/PingPing/polls2/templates/polls/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls2:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choiceID" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote" name="o">
    <input type="submit" value="Exit" name="x">
</form>

Project/PingPing/polls2/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<h1>5 latest questions</h1>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
<!--    <li><a href="/polls2/{{ question.id }}/">{{ question.question_text }}</a></li>-->
        <li><a href="{% url 'polls2:detailofques' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

Project/PingPing/polls2/templates/polls/res.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls2:detailofques' question.id %}">Vote again?</a>